name: farm_fresh_connect
description: "Farm Fresh Connect Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.20.2

  fl_chart: ^0.66.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# APP ICON CONFIG
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
